include:
  - project: cgei/gitlab/ci-includes
    file: _stages.yml
  - project: cgei/gitlab/ci-includes
    ref: master
    file: java-ci-test.yml
  - project: cgei/gitlab/ci-includes
    ref: master
    file: java-ci-package-lib.yml

ci-test:unittest:
  script:
    - mvn $MAVEN_ARGS clean test site
    - cat target/site/jacoco/index.html| grep -o 'Total[^%]*%'
  artifacts:
    paths:
      - target/site/jacoco

ci-test:spotbugs:
  when: manual
  allow_failure: true

ci-test:ensure_coverage:
  allow_failure: true

ci-package:deploy-jar:
  only:
    refs:
      - tags
      - master
